version: "3.5"
services:
  web:
    build: .
    volumes:
      - ./index.rst:/app/index.rst
      - ./in_sintesi.rst:/app/in_sintesi.rst
      - ./media:/app/media
      - ./images:/app/images
      - ./1_introduzione.rst:/app/1_introduzione.rst
      - ./2_il_cloud_computing.rst:/app/2_il_cloud_computing.rst
      - ./3_le_sfide_poste_dal_cloud_computing.rst:/app/3_le_sfide_poste_dal_cloud_computing.rst
      - ./4_la_strategia_cloud_per_la_pubblica_amministrazione.rst:/app/4_la_strategia_cloud_per_la_pubblica_amministrazione.rst
      - ./5_la_migrazione_della_pubblica_amministrazione_sul_cloud.rst:/app/5_la_migrazione_della_pubblica_amministrazione_sul_cloud.rst
      - ./6_l_adozione_della_strategia_cloud.rst:/app/6_l_adozione_della_strategia_cloud.rst
    ports:
      - "8000:8000"
